### ISSUE TITLE
Limit CRON commands

### ISSUE THREAD

**Issue by jmleroux** [FriendsOfAkeneo/FOACronBundle#10]
After some discussions with Akeneo colleagues, we feel like it would be a bit insecure to not validate the CRON command and leave the possibility to run any command.
What would you think about limiting the CRON commands to `app/console ...` ?

**Comment by nowiko** [comment]
@jmleroux this is will be valuable security improvement, as for now, there are no restrictions to run some potential malicious commands. Also possibly there should be restrictions to run some internal Symfony commands - e.g. from `doctrine:` or `fos:` scope.

**Comment by jmleroux** [comment]
Fixed by #13 and #14
