### ISSUE TITLE
Do not give access to log

### ISSUE THREAD

**Issue by jmleroux** [FriendsOfAkeneo/FOACronBundle#18]
Giving acces to log content could be a security issue.
Just create a fake cronjob with a fake (but valid) command and a system file instead of a log (like /etc/passwd).

What do you think about it ?

**Comment by alexandrzhulev** [comment]
Nice question. As a solution to restrict that log file overwrites some sensitive data (if there are enough permissions)
we could set that the only available folder for cron log files would be the application log folder (similar to where "akeneo_import_export" log files are located).
